<?php
/**
 * @file
 * Code for the Portfolio feature.
 */

include_once('portfolio.features.inc');

function portfolio_imagecache_default_presets() {
  $presets = array();
  $presets['portfolio_thumbnail'] = array (
    'presetname' => 'portfolio_thumbnail',
    'actions' => array (
      0 => array (
        'weight' => '0',
        'module' => 'imagecache',
        'action' => 'imagecache_scale_and_crop',
        'data' => array (
          'width' => '100',
          'height' => '100',
        ),
      ),
    ),
  );
  $presets['portfolio_slideshow'] = array (
    'presetname' => 'portfolio_slideshow',
    'actions' => array (
      0 => array (
        'weight' => '0',
        'module' => 'imagecache',
        'action' => 'imagecache_scale_and_crop',
        'data' => array (
          'width' => '800',
          'height' => '500',
        ),
      ),
    ),
  );
  return $presets;
}

