<?php
/**
 * @file
 * Code for the Portfolio feature.
 */

include_once('portfolio.features.inc');

function portfolio_image_default_styles() {
  $styles = array();

  $styles['portfolio_thumbnail'] = array(
    'effects' => array(
      array(
        'name' => 'portfolio_thumbnail', 
        'data' => array(
          'width' => 100,
          'height' => 100,
          'upscale' => 1,
        ), 
        'weight' => 0,
      ),
    ),
  );

  $styles['portfolio_slideshow'] = array(
    'effects' => array(
      array(
        'name' => 'portfolio_slideshow', 
        'data' => array(
          'width' => 800,
          'height' => 500,
          'upscale' => 1,
        ), 
        'weight' => 0,
      ),
    ),
  );

  return $styles;
}


